# Generated by Django 2.0.5 on 2018-09-29 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, unique=True)),
                ('web_address', models.CharField(blank=True, max_length=256, null=True)),
                ('min_words', models.IntegerField(blank=True, null=True)),
                ('max_words', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(blank=True, max_length=50, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=50, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('disposition_date', models.DateField(blank=True, null=True)),
                ('disposition_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.Disposition')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.Publisher')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
