# Generated by Django 2.0.5 on 2018-09-29 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_publisher_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_submitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='story',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
