# Generated by Django 2.0.5 on 2018-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20180929_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.CharField(max_length=50),
        ),
    ]
