# Generated by Django 2.0.5 on 2018-09-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180929_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='disposition_id',
            new_name='disposition',
        ),
    ]
