# Generated by Django 2.0.5 on 2018-09-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20180929_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
    ]
