# Generated by Django 2.0.5 on 2018-09-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20180930_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
    ]
