# Generated by Django 2.0.5 on 2018-09-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_submission_temp_disposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='temp_disposition',
        ),
    ]
